- python
- ruby
- haml
- perl
- php
- scala
- go
- xml
- lasso
- markdown
- asciidoc
- django
- handlebars
- css
- scss
- json
- javascript
- coffeescript
- actionscript
- vbscript
- vbnet
- http
- lua
- applescript
- delphi
- oxygene
- java
- cpp
- objectivec
- vala
- cs
- fsharp
- ocaml
- d
- rsl
- rib
- mel
- glsl
- sql
- smalltalk
- lisp
- clojure
- ini
- apache
- nginx
- diff
- dos
- bash
- makefile
- cmake
- axapta
- ruleslanguage
- 1c
- avasm
- vhdl
- parser3
- livecodeserver
- tex
- brainfuck
- haskell
- erlang
- erlang-repl
- rust
- matlab
- scilab
- r
- mizar
- mathematica
- profile
- autohotkey
- fix
